In [1]:
import torch

torch.load("/home/hrc/gsoc/batch_1_0/data21000_s14.pt")

Data(x=[316, 6], edge_index=[2, 6634], edge_attr=[6634, 4], y=[6634])

In [2]:
# from torch_geometric.data import Data
# from torch_geometric.loader import DataLoader

# data_list = [Data(...), ..., Data(...)]
# loader = DataLoader(data_list, batch_size=32)

In [21]:
from pathlib import Path

from torch.utils.data import Dataset  # not the one from PyG!
from torch_geometric.loader import DataLoader
import torch.nn.functional as F
from torch_geometric.nn import GCNConv


import torch


class MyDataset(Dataset):
    def __init__(self, path: Path):
        super().__init__()
        self.graphs = list(path.glob("**/*.pt"))
    
    def __getitem__(self, idx):
        return torch.load(self.graphs[idx])
    
    def __len__(self) -> int:
        return len(self.graphs)


dataset = MyDataset(Path("/home/hrc/gsoc/"))
loader = DataLoader(dataset, batch_size=32)

In [34]:
batch = next(iter(loader))

In [35]:
batch

DataBatch(x=[9569, 6], edge_index=[2, 116642], edge_attr=[116642, 4], y=[116642], batch=[9569], ptr=[33])

In [36]:
count = 0
for batch in loader:
    print(batch)
    count+=1

DataBatch(x=[9569, 6], edge_index=[2, 116642], edge_attr=[116642, 4], y=[116642], batch=[9569], ptr=[33])
DataBatch(x=[10036, 6], edge_index=[2, 127298], edge_attr=[127298, 4], y=[127298], batch=[10036], ptr=[33])
DataBatch(x=[9840, 6], edge_index=[2, 121064], edge_attr=[121064, 4], y=[121064], batch=[9840], ptr=[33])
DataBatch(x=[9770, 6], edge_index=[2, 124730], edge_attr=[124730, 4], y=[124730], batch=[9770], ptr=[33])
DataBatch(x=[9931, 6], edge_index=[2, 127558], edge_attr=[127558, 4], y=[127558], batch=[9931], ptr=[33])
DataBatch(x=[9869, 6], edge_index=[2, 139878], edge_attr=[139878, 4], y=[139878], batch=[9869], ptr=[33])
DataBatch(x=[9688, 6], edge_index=[2, 118646], edge_attr=[118646, 4], y=[118646], batch=[9688], ptr=[33])
DataBatch(x=[9827, 6], edge_index=[2, 134194], edge_attr=[134194, 4], y=[134194], batch=[9827], ptr=[33])
DataBatch(x=[9712, 6], edge_index=[2, 129030], edge_attr=[129030, 4], y=[129030], batch=[9712], ptr=[33])
DataBatch(x=[10013, 6], edge_index=[2, 13444

DataBatch(x=[9610, 6], edge_index=[2, 118564], edge_attr=[118564, 4], y=[118564], batch=[9610], ptr=[33])
DataBatch(x=[9259, 6], edge_index=[2, 112460], edge_attr=[112460, 4], y=[112460], batch=[9259], ptr=[33])
DataBatch(x=[9116, 6], edge_index=[2, 113936], edge_attr=[113936, 4], y=[113936], batch=[9116], ptr=[33])
DataBatch(x=[9213, 6], edge_index=[2, 111814], edge_attr=[111814, 4], y=[111814], batch=[9213], ptr=[33])
DataBatch(x=[8887, 6], edge_index=[2, 115462], edge_attr=[115462, 4], y=[115462], batch=[8887], ptr=[33])
DataBatch(x=[9641, 6], edge_index=[2, 126036], edge_attr=[126036, 4], y=[126036], batch=[9641], ptr=[33])
DataBatch(x=[9756, 6], edge_index=[2, 137624], edge_attr=[137624, 4], y=[137624], batch=[9756], ptr=[33])
DataBatch(x=[9747, 6], edge_index=[2, 144160], edge_attr=[144160, 4], y=[144160], batch=[9747], ptr=[33])
DataBatch(x=[9356, 6], edge_index=[2, 128544], edge_attr=[128544, 4], y=[128544], batch=[9356], ptr=[33])
DataBatch(x=[10017, 6], edge_index=[2, 123688]

DataBatch(x=[9182, 6], edge_index=[2, 124430], edge_attr=[124430, 4], y=[124430], batch=[9182], ptr=[33])
DataBatch(x=[8519, 6], edge_index=[2, 109696], edge_attr=[109696, 4], y=[109696], batch=[8519], ptr=[33])
DataBatch(x=[9682, 6], edge_index=[2, 126156], edge_attr=[126156, 4], y=[126156], batch=[9682], ptr=[33])
DataBatch(x=[9239, 6], edge_index=[2, 116990], edge_attr=[116990, 4], y=[116990], batch=[9239], ptr=[33])
DataBatch(x=[9755, 6], edge_index=[2, 127212], edge_attr=[127212, 4], y=[127212], batch=[9755], ptr=[33])
DataBatch(x=[9945, 6], edge_index=[2, 128804], edge_attr=[128804, 4], y=[128804], batch=[9945], ptr=[33])
DataBatch(x=[9510, 6], edge_index=[2, 130578], edge_attr=[130578, 4], y=[130578], batch=[9510], ptr=[33])
DataBatch(x=[9780, 6], edge_index=[2, 130056], edge_attr=[130056, 4], y=[130056], batch=[9780], ptr=[33])
DataBatch(x=[9690, 6], edge_index=[2, 126624], edge_attr=[126624, 4], y=[126624], batch=[9690], ptr=[33])
DataBatch(x=[8853, 6], edge_index=[2, 118498],

DataBatch(x=[9565, 6], edge_index=[2, 119980], edge_attr=[119980, 4], y=[119980], batch=[9565], ptr=[33])
DataBatch(x=[10074, 6], edge_index=[2, 135932], edge_attr=[135932, 4], y=[135932], batch=[10074], ptr=[33])
DataBatch(x=[9693, 6], edge_index=[2, 123270], edge_attr=[123270, 4], y=[123270], batch=[9693], ptr=[33])
DataBatch(x=[9623, 6], edge_index=[2, 122470], edge_attr=[122470, 4], y=[122470], batch=[9623], ptr=[33])
DataBatch(x=[9132, 6], edge_index=[2, 122326], edge_attr=[122326, 4], y=[122326], batch=[9132], ptr=[33])
DataBatch(x=[9618, 6], edge_index=[2, 120322], edge_attr=[120322, 4], y=[120322], batch=[9618], ptr=[33])
DataBatch(x=[9575, 6], edge_index=[2, 118214], edge_attr=[118214, 4], y=[118214], batch=[9575], ptr=[33])
DataBatch(x=[8934, 6], edge_index=[2, 110350], edge_attr=[110350, 4], y=[110350], batch=[8934], ptr=[33])
DataBatch(x=[9169, 6], edge_index=[2, 109782], edge_attr=[109782, 4], y=[109782], batch=[9169], ptr=[33])
DataBatch(x=[10242, 6], edge_index=[2, 13734

In [37]:
count

313

In [38]:
# should be 313 * 32 + 12 and it is! 
len(dataset)

9996

In [40]:
data = torch.load("/home/hrc/gsoc/batch_1_0/data21000_s14.pt")
data

Data(x=[316, 6], edge_index=[2, 6634], edge_attr=[6634, 4], y=[6634])

In [5]:
print(f'x = {data.x.shape}')
print(data.x)

x = torch.Size([316, 6])
tensor([[  0.0684,  -0.9035,  -1.4980,  -3.7805, -13.9569,  -4.3680],
        [  0.0686,  -0.9035,  -1.5020,  -3.7805, -13.9203,  -4.3556],
        [  0.1340,  -0.8955,  -1.4980,  -3.1095,  -7.0661,  -2.4080],
        ...,
        [  0.1050,  -0.9137,   1.5020,   3.3548,  -9.1744,  -2.5514],
        [  0.1128,  -0.8964,   1.4980,   3.2808,  -8.3998,  -2.8340],
        [  0.1047,  -0.9137,   1.4980,   3.3548,  -9.1993,  -2.5569]])


In [6]:
print(f'edge_index = {data.edge_index.shape}')
print(data.edge_index)

edge_index = torch.Size([2, 6634])
tensor([[  0,   0,   1,  ..., 313, 315, 314],
        [  3,   4,   3,  ..., 311, 311, 312]])


In [7]:
print(f'edge_attributes = {data.edge_attr.shape}')
print(data.edge_attr)

edge_attributes = torch.Size([6634, 4])
tensor([[-0.0092, -0.0007,  0.2000,  0.0025],
        [-0.0090, -0.0007,  0.1960,  0.0022],
        [-0.0094, -0.0007,  0.2040,  0.0024],
        ...,
        [-0.0140,  0.0012, -0.2040,  0.0045],
        [-0.0138,  0.0012, -0.2000,  0.0046],
        [-0.0149, -0.0011, -0.1960,  0.0038]])


In [8]:
print(f'y = {data.y.shape}')
print(data.y)

y = torch.Size([6634])
tensor([1., 1., 1.,  ..., 1., 1., 1.])


In [9]:
from torch_geometric.utils import to_dense_adj

A = to_dense_adj(data.edge_index)[0].numpy().astype(int)
print(f'A = {A.shape}')
print(A)

A = (316, 316)
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [10]:
print(f'y = {data.y.shape}')
print(data.y)

y = torch.Size([6634])
tensor([1., 1., 1.,  ..., 1., 1., 1.])


In [11]:
print(f'Edges are directed: {data.is_directed()}')
print(f'Graph has isolated nodes: {data.has_isolated_nodes()}')
print(f'Graph has loops: {data.has_self_loops()}')


Edges are directed: True
Graph has isolated nodes: False
Graph has loops: False


In [12]:
# Finding edge embeddings

# x = ...  # Node feature matrix: [num_nodes, num_features]
# edge_index = ... # Edge indices: [2, num_edges]

src, dst = data.edge_index
score = (data.x[src] * data.x[dst]).sum(dim=-1)

loss = F.cross_entropy(score, data.y)  # Classification

In [13]:
score

tensor([264.1794, 263.3403, 263.5314,  ..., 118.7073, 118.9811, 104.0850])

In [14]:
import torch
import torch.nn.functional as F
from torch_geometric.nn import GCNConv

class Encoder(torch.nn.Module):
    def __init__(self, in_channel, hidden_dim):
        super(Encoder, self).__init__()
        self.conv1 = GCNConv(in_channel, hidden_dim)
        self.conv2 = GCNConv(hidden_dim, hidden_dim)

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = self.conv2(x, edge_index)
        
        return x

class Decoder(torch.nn.Module):
    def __init__(self, in_channels, hidden_dim, out_channels):
        super(Decoder, self).__init__()
        self.fc1 = torch.nn.Linear(in_channels, hidden_dim)
        self.fc2 = torch.nn.Linear(hidden_dim, out_channels)

    def forward(self, x, edge_index):
        x = torch.cat([x[edge_index[0]], x[edge_index[1]]], dim=-1)
        print(x.shape)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x

class EdgeClassifier(torch.nn.Module):
    def __init__(self, in_channels, out_channels):
        super(EdgeClassifier, self).__init__()
        self.encoder = Encoder(in_channels, 32)
        self.decoder = Decoder(32 * 2, 64, out_channels)

    def forward(self, x, edge_index):
        x = self.encoder(x, edge_index)
        x = self.decoder(x, edge_index)
        return x


In [50]:
# device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
def train_model():
    model.train()
    
    loss_all = 0
    for graph_data in loader:
        optimizer.zero_grad()
        output = model(graph_data.x, graph_data.edge_index)
        print(output)
        loss = criterion(output, graph_data.y.to(torch.long))
        loss.backward()
        loss_all += loss
        optimizer.step()


In [51]:
model = EdgeClassifier(in_channels=6, out_channels=2)#.to(device)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

# Define the loss function
criterion = torch.nn.CrossEntropyLoss()

loader = DataLoader(dataset, batch_size=32)#.to(device)

# Train the model
for epoch in range(5):
    train_model()

torch.Size([116642, 64])
tensor([[ 0.2749, -0.4380],
        [ 0.2641, -0.2864],
        [ 0.2927, -0.4400],
        ...,
        [ 0.2501, -0.5813],
        [ 0.1600, -0.3121],
        [ 0.1589, -0.3119]], grad_fn=<AddmmBackward0>)
torch.Size([127298, 64])
tensor([[ 3.0920, -3.0600],
        [ 3.0922, -3.0601],
        [ 2.3965, -2.3629],
        ...,
        [ 2.7158, -2.9523],
        [ 1.4089, -1.4930],
        [ 2.9359, -3.1421]], grad_fn=<AddmmBackward0>)
torch.Size([121064, 64])
tensor([[ 1.1778, -0.9153],
        [ 1.1778, -0.9153],
        [ 1.1629, -0.9332],
        ...,
        [ 0.4613, -0.9767],
        [ 0.4612, -0.9766],
        [ 0.4260, -0.8914]], grad_fn=<AddmmBackward0>)
torch.Size([124730, 64])
tensor([[ 0.7033, -0.9025],
        [ 0.7033, -0.9025],
        [ 0.6324, -0.7885],
        ...,
        [ 0.2001, -0.2800],
        [ 0.2740, -0.5010],
        [ 0.2740, -0.5009]], grad_fn=<AddmmBackward0>)
torch.Size([127558, 64])
tensor([[ 0.7537, -1.0124],
        [ 0.753

torch.Size([117866, 64])
tensor([[ 0.1248, -0.3533],
        [ 0.2091, -0.4686],
        [ 0.2091, -0.4684],
        ...,
        [-1.1603,  0.1887],
        [-1.1605,  0.1885],
        [-1.0321,  0.1134]], grad_fn=<AddmmBackward0>)
torch.Size([121454, 64])
tensor([[ 0.1067, -0.7789],
        [ 0.1067, -0.7789],
        [ 0.1067, -0.7788],
        ...,
        [-0.8550, -0.3354],
        [-0.8378, -0.1686],
        [-0.8379, -0.1684]], grad_fn=<AddmmBackward0>)
torch.Size([126642, 64])
tensor([[-0.2737, -0.5158],
        [-0.2405, -0.4303],
        [-0.2738, -0.5157],
        ...,
        [-1.2419,  0.0808],
        [-1.2419,  0.0809],
        [-1.2419,  0.0809]], grad_fn=<AddmmBackward0>)
torch.Size([124242, 64])
tensor([[-0.1434, -0.2513],
        [-0.1434, -0.2513],
        [-0.2428, -0.1586],
        ...,
        [-1.0701,  0.2383],
        [-1.3590,  0.3194],
        [-0.8543,  0.1623]], grad_fn=<AddmmBackward0>)
torch.Size([125986, 64])
tensor([[-0.2723, -0.4048],
        [-0.272

torch.Size([122238, 64])
tensor([[-0.2889, -0.0260],
        [-0.2717, -0.0703],
        [-0.3368, -0.0347],
        ...,
        [-2.0220,  0.5091],
        [-2.0221,  0.5091],
        [-1.6295,  0.4198]], grad_fn=<AddmmBackward0>)
torch.Size([112468, 64])
tensor([[-3.7764e-01, -6.1226e-02],
        [-3.7762e-01, -6.1249e-02],
        [-3.5217e-01,  1.6578e-03],
        ...,
        [-2.0696e+00,  6.6490e-01],
        [-2.1682e+00,  7.3005e-01],
        [-2.1681e+00,  7.3006e-01]], grad_fn=<AddmmBackward0>)
torch.Size([122348, 64])
tensor([[-0.3155, -0.0604],
        [-0.3155, -0.0604],
        [-0.3155, -0.0604],
        ...,
        [-1.8753,  0.5829],
        [-2.0605,  0.6378],
        [-2.0604,  0.6378]], grad_fn=<AddmmBackward0>)
torch.Size([117172, 64])
tensor([[-0.4851,  0.0828],
        [-0.4235,  0.0497],
        [-0.4281,  0.0696],
        ...,
        [-2.0651,  0.6180],
        [-2.0652,  0.6180],
        [-2.0493,  0.5951]], grad_fn=<AddmmBackward0>)
torch.Size([120780, 

torch.Size([132598, 64])
tensor([[-0.5026, -0.2045],
        [-0.5027, -0.2044],
        [-0.5026, -0.2046],
        ...,
        [-1.7686,  0.4207],
        [-1.7687,  0.4207],
        [-1.8809,  0.3970]], grad_fn=<AddmmBackward0>)
torch.Size([138266, 64])
tensor([[-0.0694, -0.0571],
        [-0.2225, -0.1433],
        [-0.1252, -0.0528],
        ...,
        [-2.0734,  0.7498],
        [-1.9359,  0.5892],
        [-1.9358,  0.5892]], grad_fn=<AddmmBackward0>)
torch.Size([117178, 64])
tensor([[-0.2663, -0.1441],
        [-0.2662, -0.1441],
        [-0.2746, -0.2025],
        ...,
        [-1.7730,  0.3924],
        [-1.8225,  0.4490],
        [-1.7870,  0.4545]], grad_fn=<AddmmBackward0>)
torch.Size([137778, 64])
tensor([[-0.2703, -0.2101],
        [-0.2703, -0.2102],
        [-0.3067, -0.1728],
        ...,
        [-1.8897,  0.6924],
        [-1.8580,  0.6475],
        [-1.8581,  0.6474]], grad_fn=<AddmmBackward0>)
torch.Size([112668, 64])
tensor([[-0.1329, -0.1401],
        [-0.132

tensor([[-0.0945, -0.2038],
        [-0.0945, -0.2038],
        [-0.1664, -0.1593],
        ...,
        [-1.9064,  0.2090],
        [-2.2663,  0.2703],
        [-2.2661,  0.2704]], grad_fn=<AddmmBackward0>)
torch.Size([130860, 64])
tensor([[-0.3997, -0.1543],
        [-0.3997, -0.1544],
        [-0.3536, -0.1893],
        ...,
        [-1.5581,  0.5315],
        [-1.5583,  0.5318],
        [-1.3956,  0.2900]], grad_fn=<AddmmBackward0>)
torch.Size([125230, 64])
tensor([[-0.3841,  0.0220],
        [-0.3841,  0.0220],
        [-0.3841,  0.0221],
        ...,
        [-2.0271,  0.2629],
        [-2.0590,  0.2768],
        [-1.7927,  0.1852]], grad_fn=<AddmmBackward0>)
torch.Size([132446, 64])
tensor([[-0.4687, -0.1531],
        [-0.4686, -0.1532],
        [-0.4173, -0.1336],
        ...,
        [-1.8277,  0.1865],
        [-1.6693,  0.1612],
        [-2.0762,  0.2823]], grad_fn=<AddmmBackward0>)
torch.Size([122010, 64])
tensor([[-0.4011, -0.1671],
        [-0.4012, -0.1671],
        [-0.

tensor([[-0.3186, -0.5197],
        [-0.3310, -0.6546],
        [-0.3119, -0.5710],
        ...,
        [-2.1030,  0.1444],
        [-1.8142,  0.0149],
        [-1.8143,  0.0148]], grad_fn=<AddmmBackward0>)
torch.Size([124906, 64])
tensor([[-0.1581, -0.5229],
        [-0.1581, -0.5229],
        [-0.1580, -0.5230],
        ...,
        [-1.8252,  0.0718],
        [-1.8861, -0.0634],
        [-1.8859, -0.0633]], grad_fn=<AddmmBackward0>)
torch.Size([124908, 64])
tensor([[-0.4451, -0.2832],
        [-0.4450, -0.2832],
        [-0.1627, -0.5540],
        ...,
        [-1.5497, -0.0641],
        [-1.4205, -0.1386],
        [-1.6786, -0.0167]], grad_fn=<AddmmBackward0>)
torch.Size([125872, 64])
tensor([[-0.2579, -0.3355],
        [-0.4075, -0.2538],
        [-0.3339, -0.3818],
        ...,
        [-1.4715,  0.1672],
        [-1.4230,  0.1912],
        [-1.4231,  0.1916]], grad_fn=<AddmmBackward0>)
torch.Size([145102, 64])
tensor([[-0.4319, -0.2010],
        [-0.4319, -0.2010],
        [-0.

tensor([[-0.7170, -0.1675],
        [-0.8416, -0.1239],
        [-0.8416, -0.1239],
        ...,
        [-1.2263,  0.3921],
        [-1.4427,  0.5144],
        [-1.3637,  0.4340]], grad_fn=<AddmmBackward0>)
torch.Size([113694, 64])
tensor([[-0.4185, -0.2847],
        [-0.3393, -0.3915],
        [-0.4053, -0.3854],
        ...,
        [-1.7557,  0.4600],
        [-1.7561,  0.4606],
        [-1.7558,  0.4600]], grad_fn=<AddmmBackward0>)
torch.Size([126216, 64])
tensor([[-0.3210, -0.6278],
        [-0.3994, -0.4587],
        [-0.3995, -0.4587],
        ...,
        [-1.7413, -0.0198],
        [-1.7414, -0.0199],
        [-1.7413, -0.0198]], grad_fn=<AddmmBackward0>)
torch.Size([127974, 64])
tensor([[-0.6158, -0.2828],
        [-0.6158, -0.2828],
        [-0.6157, -0.2830],
        ...,
        [-1.4744,  0.0645],
        [-1.4497, -0.0228],
        [-1.4743,  0.0645]], grad_fn=<AddmmBackward0>)
torch.Size([126634, 64])
tensor([[-0.5358, -0.4977],
        [-0.5358, -0.4977],
        [-0.

torch.Size([129092, 64])
tensor([[-0.6835, -0.3032],
        [-0.7339, -0.4782],
        [-0.7339, -0.4783],
        ...,
        [-2.4114,  0.4544],
        [-2.3873,  0.4763],
        [-2.3874,  0.4761]], grad_fn=<AddmmBackward0>)
torch.Size([128706, 64])
tensor([[-0.5244, -0.4219],
        [-0.3637, -0.7040],
        [-0.3637, -0.7040],
        ...,
        [-1.9251,  0.5558],
        [-2.0463,  0.5962],
        [-2.0463,  0.5965]], grad_fn=<AddmmBackward0>)
torch.Size([117078, 64])
tensor([[-0.2752, -0.8264],
        [-0.2752, -0.8264],
        [-0.3453, -0.7920],
        ...,
        [-1.7754,  0.3913],
        [-1.7205,  0.3912],
        [-1.7485,  0.3241]], grad_fn=<AddmmBackward0>)
torch.Size([137238, 64])
tensor([[-0.5538, -0.4582],
        [-0.5538, -0.4582],
        [-0.5244, -0.4883],
        ...,
        [-1.6550, -0.0185],
        [-1.7056, -0.0735],
        [-1.7055, -0.0734]], grad_fn=<AddmmBackward0>)
torch.Size([119980, 64])
tensor([[-0.8016, -0.2666],
        [-0.801

torch.Size([122888, 64])
tensor([[-0.5799, -0.4661],
        [-0.5799, -0.4661],
        [-0.7263, -0.3696],
        ...,
        [-1.2686, -0.0534],
        [-1.2528, -0.1202],
        [-1.2529, -0.1200]], grad_fn=<AddmmBackward0>)
torch.Size([129072, 64])
tensor([[-0.2845, -0.7786],
        [-0.2845, -0.7787],
        [-0.3034, -0.7519],
        ...,
        [-1.4064, -0.0738],
        [-1.4064, -0.0738],
        [-1.4064, -0.0737]], grad_fn=<AddmmBackward0>)
torch.Size([133006, 64])
tensor([[-0.5796, -0.4755],
        [-0.6933, -0.4381],
        [-0.6932, -0.4381],
        ...,
        [-1.6396,  0.1849],
        [-1.8832,  0.1389],
        [-1.8831,  0.1391]], grad_fn=<AddmmBackward0>)
torch.Size([128906, 64])
tensor([[-0.5077, -0.3289],
        [-0.5077, -0.3289],
        [-0.3841, -0.4594],
        ...,
        [-1.9884,  0.5236],
        [-2.0210,  0.5589],
        [-1.9883,  0.5235]], grad_fn=<AddmmBackward0>)
torch.Size([144960, 64])
tensor([[-0.1099, -0.9181],
        [-0.109

torch.Size([123130, 64])
tensor([[-0.8368, -0.0402],
        [-0.8007, -0.0133],
        [-0.9838,  0.2159],
        ...,
        [-2.0331,  0.6597],
        [-1.8094,  0.6502],
        [-2.0842,  0.7724]], grad_fn=<AddmmBackward0>)
torch.Size([135848, 64])
tensor([[-1.0053, -0.1427],
        [-1.0053, -0.1427],
        [-0.2774, -1.0156],
        ...,
        [-2.1149,  0.4197],
        [-2.0952,  0.3932],
        [-2.0953,  0.3932]], grad_fn=<AddmmBackward0>)
torch.Size([108688, 64])
tensor([[-0.7348, -0.3592],
        [-0.7349, -0.3591],
        [-0.8155, -0.1819],
        ...,
        [-1.8621,  0.6325],
        [-1.7237,  0.4907],
        [-1.7238,  0.4908]], grad_fn=<AddmmBackward0>)
torch.Size([134728, 64])
tensor([[-0.7567, -0.3260],
        [-0.5725, -0.6017],
        [-0.5726, -0.6016],
        ...,
        [-1.9083,  0.4608],
        [-2.0599,  0.6084],
        [-2.0598,  0.6088]], grad_fn=<AddmmBackward0>)
torch.Size([113464, 64])
tensor([[-0.7876, -0.3840],
        [-0.787

torch.Size([131096, 64])
tensor([[-0.6920, -0.3417],
        [-0.8179,  0.0521],
        [-0.8180,  0.0521],
        ...,
        [-1.7672,  0.6071],
        [-1.9529,  0.9298],
        [-1.9526,  0.9299]], grad_fn=<AddmmBackward0>)
torch.Size([118558, 64])
tensor([[-0.4658, -0.8850],
        [-0.4658, -0.8850],
        [-0.1108, -1.3819],
        ...,
        [-1.7667,  0.6449],
        [-1.9669,  0.5859],
        [-1.9664,  0.5852]], grad_fn=<AddmmBackward0>)
torch.Size([120524, 64])
tensor([[-1.2334,  0.0785],
        [-1.2333,  0.0784],
        [-0.7685, -0.2693],
        ...,
        [-1.9476,  0.8248],
        [-1.9232,  0.8431],
        [-1.9234,  0.8431]], grad_fn=<AddmmBackward0>)
torch.Size([143658, 64])
tensor([[-1.2036, -0.0537],
        [-1.2037, -0.0536],
        [-1.2038, -0.0534],
        ...,
        [-1.4791,  0.4060],
        [-1.7721,  0.7823],
        [-1.7723,  0.7823]], grad_fn=<AddmmBackward0>)
torch.Size([143670, 64])
tensor([[ 0.2460, -1.3054],
        [ 0.245

torch.Size([111814, 64])
tensor([[-0.9949,  0.0111],
        [-0.4014, -0.6670],
        [-0.4862, -0.5615],
        ...,
        [-1.8229,  0.7506],
        [-1.7406,  0.6073],
        [-1.8229,  0.7506]], grad_fn=<AddmmBackward0>)
torch.Size([115462, 64])
tensor([[-0.7767, -0.1576],
        [-0.7768, -0.1574],
        [-0.9333,  0.1213],
        ...,
        [-1.3978,  0.3511],
        [-1.4537,  0.3517],
        [-1.4536,  0.3518]], grad_fn=<AddmmBackward0>)
torch.Size([126036, 64])
tensor([[-0.4738, -0.4573],
        [-0.4740, -0.4572],
        [-0.6531, -0.3280],
        ...,
        [-1.6369,  0.1180],
        [-1.6363,  0.1168],
        [-1.4002,  0.2187]], grad_fn=<AddmmBackward0>)
torch.Size([137624, 64])
tensor([[-0.3440, -0.7085],
        [-0.3439, -0.7086],
        [-0.6255, -0.4680],
        ...,
        [-2.0491,  0.5346],
        [-2.0489,  0.5347],
        [-2.0491,  0.5346]], grad_fn=<AddmmBackward0>)
torch.Size([144160, 64])
tensor([[-0.6573, -0.2770],
        [-0.657

tensor([[-0.7767, -0.5263],
        [-0.7767, -0.5263],
        [-0.9215, -0.1800],
        ...,
        [-2.1376,  0.6425],
        [-2.1373,  0.6426],
        [-2.1376,  0.6425]], grad_fn=<AddmmBackward0>)
torch.Size([120208, 64])
tensor([[-1.0205, -0.0652],
        [-1.0204, -0.0653],
        [-0.8000, -0.2102],
        ...,
        [-1.8808,  0.4826],
        [-2.2314,  0.4811],
        [-2.2314,  0.4813]], grad_fn=<AddmmBackward0>)
torch.Size([107886, 64])
tensor([[-1.0991,  0.2636],
        [-1.0992,  0.2637],
        [-1.0987,  0.2631],
        ...,
        [-1.7465,  0.1759],
        [-1.8191,  0.1961],
        [-1.9941,  0.2162]], grad_fn=<AddmmBackward0>)
torch.Size([123250, 64])
tensor([[-0.7467, -0.1195],
        [-0.7468, -0.1194],
        [-0.7654, -0.1503],
        ...,
        [-1.5890,  0.0552],
        [-1.6595,  0.1192],
        [-1.6597,  0.1192]], grad_fn=<AddmmBackward0>)
torch.Size([133478, 64])
tensor([[-0.3459, -0.6255],
        [-0.3457, -0.6257],
        [-0.

tensor([[-0.8360,  0.2046],
        [-0.3013, -0.3574],
        [-0.8215,  0.1649],
        ...,
        [-1.4296,  0.2101],
        [-1.4767,  0.2364],
        [-1.5576,  0.3446]], grad_fn=<AddmmBackward0>)
torch.Size([121240, 64])
tensor([[-0.5346, -0.4653],
        [-0.5344, -0.4656],
        [-0.8057, -0.0838],
        ...,
        [-1.5792,  0.2843],
        [-1.4419,  0.2622],
        [-1.4317,  0.2684]], grad_fn=<AddmmBackward0>)
torch.Size([127024, 64])
tensor([[-0.6878, -0.4258],
        [-0.6878, -0.4258],
        [-0.9481, -0.1593],
        ...,
        [-2.5250,  0.7073],
        [-1.7131,  0.3596],
        [-1.7294,  0.3532]], grad_fn=<AddmmBackward0>)
torch.Size([131610, 64])
tensor([[-1.7205,  0.4650],
        [-1.7205,  0.4650],
        [-0.9882,  0.1418],
        ...,
        [-1.9585,  0.5433],
        [-1.7615,  0.4927],
        [-1.9667,  0.5496]], grad_fn=<AddmmBackward0>)
torch.Size([116116, 64])
tensor([[-0.7206, -0.1762],
        [-0.7205, -0.1762],
        [-0.

torch.Size([149030, 64])
tensor([[-0.6407, -0.4165],
        [-0.6407, -0.4165],
        [-1.0699,  0.0745],
        ...,
        [-1.6712,  0.2048],
        [-1.6932,  0.2183],
        [-1.8359,  0.2252]], grad_fn=<AddmmBackward0>)
torch.Size([122694, 64])
tensor([[-1.0715, -0.1722],
        [-1.0715, -0.1723],
        [ 0.0269, -1.3055],
        ...,
        [-1.9112,  0.2969],
        [-1.6601,  0.1696],
        [-1.6602,  0.1695]], grad_fn=<AddmmBackward0>)
torch.Size([129450, 64])
tensor([[-1.5350,  0.3583],
        [-1.5349,  0.3583],
        [-0.6249, -0.5058],
        ...,
        [-2.2416,  0.3495],
        [-2.2413,  0.3496],
        [-1.6005,  0.1846]], grad_fn=<AddmmBackward0>)
torch.Size([121746, 64])
tensor([[-1.1704,  0.2131],
        [-1.1703,  0.2130],
        [-1.1704,  0.2131],
        ...,
        [-1.7575,  0.1754],
        [-1.8190,  0.1719],
        [-1.8189,  0.1720]], grad_fn=<AddmmBackward0>)
torch.Size([111834, 64])
tensor([[-0.6777, -0.3396],
        [-0.677

torch.Size([111902, 64])
tensor([[-1.2010, -0.0067],
        [-1.2009, -0.0069],
        [-1.2019, -0.0057],
        ...,
        [-1.5026,  0.2639],
        [-1.5025,  0.2640],
        [-1.4401,  0.2646]], grad_fn=<AddmmBackward0>)
torch.Size([118318, 64])
tensor([[-1.1394,  0.1611],
        [-1.0356,  0.1270],
        [ 0.5829, -1.8072],
        ...,
        [-2.4352,  0.3150],
        [-2.4353,  0.3147],
        [-2.2526,  0.3854]], grad_fn=<AddmmBackward0>)
torch.Size([137742, 64])
tensor([[-1.0543,  0.0895],
        [-1.1766,  0.2714],
        [-0.9514, -0.0070],
        ...,
        [-1.9420,  0.2989],
        [-1.6509,  0.2425],
        [-1.6510,  0.2425]], grad_fn=<AddmmBackward0>)
torch.Size([124598, 64])
tensor([[-1.4102,  0.5764],
        [-1.1440,  0.1830],
        [-1.1438,  0.1829],
        ...,
        [-1.9452,  0.2982],
        [-2.4342,  0.5560],
        [-2.4342,  0.5564]], grad_fn=<AddmmBackward0>)
torch.Size([123456, 64])
tensor([[-1.5221,  0.3556],
        [-1.522

torch.Size([118214, 64])
tensor([[-0.7797, -0.3148],
        [-0.7798, -0.3147],
        [-1.0236,  0.0230],
        ...,
        [-1.7812,  0.1540],
        [-1.9990,  0.2785],
        [-1.9992,  0.2784]], grad_fn=<AddmmBackward0>)
torch.Size([110350, 64])
tensor([[-1.2211,  0.0963],
        [-1.2212,  0.0964],
        [-1.7288,  0.7128],
        ...,
        [-2.0342,  0.7184],
        [-1.7251,  0.4025],
        [-1.7249,  0.4025]], grad_fn=<AddmmBackward0>)
torch.Size([109782, 64])
tensor([[ 0.3284, -1.6223],
        [ 0.3288, -1.6227],
        [-1.2572,  0.2258],
        ...,
        [-2.0339,  0.6241],
        [-2.0341,  0.6241],
        [-2.1918,  0.8487]], grad_fn=<AddmmBackward0>)
torch.Size([137344, 64])
tensor([[-1.2275,  0.0032],
        [-1.2277,  0.0035],
        [-1.0285, -0.1641],
        ...,
        [-2.8461,  0.8174],
        [-1.9599,  0.4689],
        [-2.5488,  0.6903]], grad_fn=<AddmmBackward0>)
torch.Size([119524, 64])
tensor([[-1.3105,  0.3385],
        [-1.424

torch.Size([133792, 64])
tensor([[-0.9927, -0.0461],
        [-0.9926, -0.0462],
        [-1.0179, -0.0134],
        ...,
        [-1.9446,  0.4149],
        [-1.6929,  0.3098],
        [-1.6930,  0.3098]], grad_fn=<AddmmBackward0>)
torch.Size([111570, 64])
tensor([[ 0.8841, -2.0219],
        [-1.3533,  0.3484],
        [-1.6232,  0.6737],
        ...,
        [-2.0986,  0.4730],
        [-1.7873,  0.3544],
        [-1.7874,  0.3544]], grad_fn=<AddmmBackward0>)
torch.Size([121936, 64])
tensor([[-2.0278,  0.8898],
        [-2.0276,  0.8895],
        [-0.8303, -0.2665],
        ...,
        [-1.9786,  0.5050],
        [-1.9789,  0.5049],
        [-2.3309,  0.5496]], grad_fn=<AddmmBackward0>)
torch.Size([125680, 64])
tensor([[-0.5268, -0.4524],
        [-0.5281, -0.4510],
        [ 0.3323, -1.4447],
        ...,
        [-2.3034,  0.8032],
        [-2.1490,  0.6059],
        [-2.1489,  0.6060]], grad_fn=<AddmmBackward0>)
torch.Size([142686, 64])
tensor([[-1.2288,  0.0432],
        [-1.228

torch.Size([110908, 64])
tensor([[-1.2101,  0.3310],
        [-1.2100,  0.3309],
        [-0.8643, -0.1098],
        ...,
        [-1.7873,  0.3827],
        [-2.3708,  0.6544],
        [-2.3705,  0.6544]], grad_fn=<AddmmBackward0>)
torch.Size([119316, 64])
tensor([[-1.4344,  0.3664],
        [-1.4344,  0.3664],
        [-1.4127,  0.4493],
        ...,
        [-2.3070,  0.8781],
        [-2.3071,  0.8780],
        [-1.9770,  0.6389]], grad_fn=<AddmmBackward0>)
torch.Size([126074, 64])
tensor([[-1.4550,  0.4241],
        [-1.4549,  0.4241],
        [-0.6982, -0.4452],
        ...,
        [-2.0288,  0.5690],
        [-1.4645,  0.2830],
        [-1.5836,  0.3411]], grad_fn=<AddmmBackward0>)
torch.Size([95366, 64])
tensor([[-1.8005,  0.8217],
        [-1.8005,  0.8217],
        [-1.1402,  0.1052],
        ...,
        [-1.6006,  0.3162],
        [-1.9411,  0.3284],
        [-1.6577,  0.3284]], grad_fn=<AddmmBackward0>)
torch.Size([129498, 64])
tensor([[-1.5236,  0.3559],
        [-1.9072

torch.Size([131308, 64])
tensor([[-1.8060,  0.8056],
        [-1.9820,  0.8976],
        [-2.3214,  1.2275],
        ...,
        [-1.9428,  0.2125],
        [-1.9428,  0.2124],
        [-1.9427,  0.2125]], grad_fn=<AddmmBackward0>)
torch.Size([120108, 64])
tensor([[-1.7537,  0.5974],
        [-1.7540,  0.5977],
        [-1.7529,  0.5964],
        ...,
        [-1.5191,  0.2189],
        [-1.5554,  0.2187],
        [-1.5553,  0.2187]], grad_fn=<AddmmBackward0>)
torch.Size([133258, 64])
tensor([[-1.3459,  0.4271],
        [-0.7856, -0.2249],
        [-0.7857, -0.2247],
        ...,
        [-2.1898,  0.3781],
        [-2.3563,  0.3318],
        [-2.3561,  0.3320]], grad_fn=<AddmmBackward0>)
torch.Size([122140, 64])
tensor([[-0.5251, -0.6424],
        [-0.5260, -0.6415],
        [-0.5252, -0.6423],
        ...,
        [-1.6459,  0.0527],
        [-1.8670,  0.2177],
        [-1.4133,  0.0996]], grad_fn=<AddmmBackward0>)
torch.Size([121160, 64])
tensor([[-1.7144,  0.8175],
        [ 0.267

torch.Size([128056, 64])
tensor([[-2.0705,  0.9712],
        [-1.4022,  0.3233],
        [-1.4028,  0.3238],
        ...,
        [-1.6604,  0.2754],
        [-2.1146,  0.4831],
        [-2.1145,  0.4832]], grad_fn=<AddmmBackward0>)
torch.Size([109678, 64])
tensor([[-2.2114,  1.3634],
        [-2.2107,  1.3626],
        [-1.2300,  0.3416],
        ...,
        [-1.9659,  0.4607],
        [-1.8401,  0.3004],
        [-1.8402,  0.3003]], grad_fn=<AddmmBackward0>)
torch.Size([134124, 64])
tensor([[-0.1181, -0.8811],
        [-0.1181, -0.8812],
        [-0.1181, -0.8811],
        ...,
        [-2.0098,  0.6457],
        [-2.1797,  0.6719],
        [-2.1796,  0.6720]], grad_fn=<AddmmBackward0>)
torch.Size([130748, 64])
tensor([[-0.8727, -0.3429],
        [-0.8720, -0.3435],
        [-1.5391,  0.3810],
        ...,
        [-1.4753,  0.0710],
        [-1.4103,  0.0402],
        [-1.4103,  0.0402]], grad_fn=<AddmmBackward0>)
torch.Size([104230, 64])
tensor([[-1.0538,  0.1031],
        [-1.053

torch.Size([123040, 64])
tensor([[-1.3144,  0.3864],
        [-1.3142,  0.3863],
        [-0.9796, -0.0383],
        ...,
        [-1.2894,  0.1946],
        [-1.3662,  0.1531],
        [-1.3231,  0.1721]], grad_fn=<AddmmBackward0>)
torch.Size([124120, 64])
tensor([[-1.3773,  0.5250],
        [-1.3775,  0.5252],
        [-1.3588,  0.4999],
        ...,
        [-1.6827,  0.3649],
        [-1.3591,  0.1663],
        [-1.6223,  0.2483]], grad_fn=<AddmmBackward0>)
torch.Size([131058, 64])
tensor([[-1.8024,  0.7875],
        [-1.8027,  0.7879],
        [-2.0026,  1.0193],
        ...,
        [-1.5886,  0.2090],
        [-1.6480,  0.1930],
        [-1.5539,  0.2238]], grad_fn=<AddmmBackward0>)
torch.Size([138398, 64])
tensor([[-0.8420, -0.3720],
        [-0.8432, -0.3708],
        [-2.0646,  1.0464],
        ...,
        [-1.2677,  0.2958],
        [-1.6536,  0.4817],
        [-1.7685,  0.3914]], grad_fn=<AddmmBackward0>)
torch.Size([129196, 64])
tensor([[-1.5090,  0.7832],
        [-1.138

torch.Size([126050, 64])
tensor([[-0.9101,  0.0386],
        [-0.9107,  0.0392],
        [-1.4378,  0.5090],
        ...,
        [-1.8033,  0.0887],
        [-1.8034,  0.0886],
        [-2.0304,  0.2450]], grad_fn=<AddmmBackward0>)
torch.Size([124152, 64])
tensor([[-0.9708, -0.2735],
        [-0.9717, -0.2726],
        [-1.2964,  0.2268],
        ...,
        [-1.8429,  0.1634],
        [-1.9270,  0.1329],
        [-1.8057,  0.1797]], grad_fn=<AddmmBackward0>)
torch.Size([124430, 64])
tensor([[-2.3080,  1.3150],
        [-1.6113,  0.4445],
        [-1.6101,  0.4435],
        ...,
        [-1.6041,  0.1847],
        [-1.7573,  0.3118],
        [-1.7574,  0.3115]], grad_fn=<AddmmBackward0>)
torch.Size([109696, 64])
tensor([[-1.6158,  0.7503],
        [-1.6156,  0.7501],
        [-2.0290,  1.1534],
        ...,
        [-1.1520, -0.0069],
        [-1.1519, -0.0069],
        [-1.7877, -0.0142]], grad_fn=<AddmmBackward0>)
torch.Size([126156, 64])
tensor([[-1.1110,  0.2453],
        [-1.111

torch.Size([133562, 64])
tensor([[-1.2335,  0.2678],
        [-1.2330,  0.2673],
        [ 0.9753, -2.3372],
        ...,
        [-2.1640,  0.2834],
        [-2.1641,  0.2830],
        [-1.9037,  0.2451]], grad_fn=<AddmmBackward0>)
torch.Size([125432, 64])
tensor([[-1.6017,  0.8581],
        [-1.6015,  0.8579],
        [-1.4072,  0.5728],
        ...,
        [-1.7682,  0.2700],
        [-1.7680,  0.2698],
        [-1.7683,  0.2699]], grad_fn=<AddmmBackward0>)
torch.Size([132940, 64])
tensor([[-1.9888,  1.0810],
        [-1.7454,  0.8313],
        [-1.7450,  0.8309],
        ...,
        [-1.8763,  0.2131],
        [-1.8763,  0.2131],
        [-1.8763,  0.2131]], grad_fn=<AddmmBackward0>)
torch.Size([123608, 64])
tensor([[-1.5197,  0.5115],
        [-0.7356, -0.1850],
        [-0.9584, -0.0606],
        ...,
        [-2.3120,  0.5641],
        [-2.3122,  0.5639],
        [-2.3121,  0.5641]], grad_fn=<AddmmBackward0>)
torch.Size([127958, 64])
tensor([[-2.2741,  1.3706],
        [-2.274

torch.Size([140406, 64])
tensor([[-1.7073,  0.7890],
        [-1.8224,  0.8541],
        [-1.8232,  0.8547],
        ...,
        [-1.9889,  0.3582],
        [-2.1571,  0.5009],
        [-2.1572,  0.5008]], grad_fn=<AddmmBackward0>)
torch.Size([108314, 64])
tensor([[-2.5057,  1.5319],
        [-1.4468,  0.4483],
        [-1.4470,  0.4485],
        ...,
        [-1.3844,  0.1592],
        [-2.1478,  0.7328],
        [-2.1477,  0.7329]], grad_fn=<AddmmBackward0>)
torch.Size([117570, 64])
tensor([[-1.8313,  0.8038],
        [-1.8305,  0.8031],
        [-2.5421,  1.4995],
        ...,
        [-1.7405,  0.2944],
        [-1.6416,  0.2219],
        [-1.6417,  0.2219]], grad_fn=<AddmmBackward0>)
torch.Size([135434, 64])
tensor([[-2.4899,  1.4671],
        [-1.6141,  0.6538],
        [-1.6136,  0.6533],
        ...,
        [-2.0344,  0.5158],
        [-2.0345,  0.5157],
        [-1.8815,  0.4949]], grad_fn=<AddmmBackward0>)
torch.Size([109628, 64])
tensor([[-0.7603, -0.1506],
        [-0.760

tensor([[-1.6063,  1.0388],
        [-2.2464,  1.2484],
        [-1.9410,  0.9757],
        ...,
        [-1.4207,  0.2041],
        [-1.8450,  0.4597],
        [-1.8451,  0.4597]], grad_fn=<AddmmBackward0>)
torch.Size([112358, 64])
tensor([[-1.1850,  0.5524],
        [-1.3882,  0.6689],
        [-1.2711,  0.5719],
        ...,
        [-2.0362,  0.4965],
        [-2.0363,  0.4964],
        [-1.6934,  0.3007]], grad_fn=<AddmmBackward0>)
torch.Size([126466, 64])
tensor([[-1.1305,  0.4385],
        [-1.0909,  0.3663],
        [-1.0675,  0.3651],
        ...,
        [-1.7606,  0.4469],
        [-1.6757,  0.3615],
        [-1.4222,  0.2338]], grad_fn=<AddmmBackward0>)
torch.Size([129568, 64])
tensor([[ 1.1430, -2.3393],
        [-0.0846, -1.1041],
        [-0.0852, -1.1036],
        ...,
        [-1.3222,  0.2306],
        [-1.2590,  0.2267],
        [-1.2590,  0.2267]], grad_fn=<AddmmBackward0>)
torch.Size([137170, 64])
tensor([[-1.9336,  0.8976],
        [-1.9339,  0.8979],
        [-1.

tensor([[-1.9422,  1.0140],
        [-1.1501,  0.4190],
        [-1.6022,  0.6310],
        ...,
        [-1.4600,  0.2634],
        [-1.7385,  0.3381],
        [-1.7384,  0.3382]], grad_fn=<AddmmBackward0>)
torch.Size([141916, 64])
tensor([[-1.0571,  0.0731],
        [-1.0558,  0.0718],
        [-2.4236,  1.4145],
        ...,
        [-1.9103,  0.4721],
        [-1.5674,  0.2368],
        [-1.5674,  0.2368]], grad_fn=<AddmmBackward0>)
torch.Size([149676, 64])
tensor([[-2.0725,  1.0965],
        [-2.0734,  1.0974],
        [-2.5457,  1.6123],
        ...,
        [-2.1778,  0.7483],
        [-2.1775,  0.7484],
        [-1.6788,  0.2855]], grad_fn=<AddmmBackward0>)
torch.Size([111686, 64])
tensor([[-2.5433,  1.5546],
        [-2.7505,  1.7792],
        [-2.6894,  1.6797],
        ...,
        [-1.8284,  0.4265],
        [-1.8100,  0.4541],
        [-1.8098,  0.4542]], grad_fn=<AddmmBackward0>)
torch.Size([47198, 64])
tensor([[-1.6604,  0.9325],
        [-1.6607,  0.9329],
        [-1.7

torch.Size([115624, 64])
tensor([[-0.0211, -0.8855],
        [ 0.0364, -0.6250],
        [-0.6234,  0.0701],
        ...,
        [-2.0328,  0.5516],
        [-1.9410,  0.5300],
        [-1.4593,  0.2804]], grad_fn=<AddmmBackward0>)
torch.Size([128176, 64])
tensor([[-1.4944,  0.7148],
        [-1.4949,  0.7152],
        [-1.5372,  0.7033],
        ...,
        [-1.2357,  0.2137],
        [-1.2368,  0.2139],
        [-1.7380,  0.4641]], grad_fn=<AddmmBackward0>)
torch.Size([142390, 64])
tensor([[-2.3795,  1.3437],
        [-2.3795,  1.3437],
        [-2.3175,  1.1734],
        ...,
        [-2.0398,  0.5817],
        [-2.1299,  0.6854],
        [-2.1301,  0.6853]], grad_fn=<AddmmBackward0>)
torch.Size([120304, 64])
tensor([[-1.8428,  0.9440],
        [-1.8432,  0.9444],
        [-1.8423,  0.9433],
        ...,
        [-1.8961,  0.4715],
        [-1.8963,  0.4714],
        [-1.4331,  0.2636]], grad_fn=<AddmmBackward0>)
torch.Size([119222, 64])
tensor([[-1.0351,  0.1244],
        [-1.367

torch.Size([108086, 64])
tensor([[-1.5224,  0.4520],
        [-1.5221,  0.4517],
        [-1.5223,  0.4519],
        ...,
        [-1.9923,  0.5903],
        [-1.8963,  0.5720],
        [-1.8960,  0.5721]], grad_fn=<AddmmBackward0>)
torch.Size([114006, 64])
tensor([[-2.1249,  1.2632],
        [-2.1244,  1.2628],
        [-2.3462,  1.3514],
        ...,
        [-1.4541,  0.3593],
        [-1.4956,  0.3726],
        [-2.0587,  0.7815]], grad_fn=<AddmmBackward0>)
torch.Size([121282, 64])
tensor([[-2.1611,  1.1098],
        [-2.5249,  1.5472],
        [-1.2540,  0.1615],
        ...,
        [-1.3900,  0.2602],
        [-1.3900,  0.2602],
        [-1.3900,  0.2602]], grad_fn=<AddmmBackward0>)
torch.Size([128060, 64])
tensor([[-2.0218,  0.9269],
        [-2.0217,  0.9268],
        [-2.0386,  1.2965],
        ...,
        [-1.9277,  0.5400],
        [-1.9280,  0.5401],
        [-1.4928,  0.3363]], grad_fn=<AddmmBackward0>)
torch.Size([122238, 64])
tensor([[-1.8639,  0.8437],
        [-1.910

torch.Size([115186, 64])
tensor([[-1.8875,  0.8615],
        [-1.2038,  0.2029],
        [-1.4088,  0.5421],
        ...,
        [-0.9804,  0.0781],
        [-1.0737,  0.1802],
        [-1.0737,  0.1803]], grad_fn=<AddmmBackward0>)
torch.Size([130998, 64])
tensor([[-1.9623,  0.7639],
        [-2.1002,  0.8615],
        [-2.1007,  0.8620],
        ...,
        [-1.8200,  0.3410],
        [-1.3198,  0.0368],
        [-1.4998,  0.1507]], grad_fn=<AddmmBackward0>)
torch.Size([132598, 64])
tensor([[-1.7670,  0.6927],
        [-1.7675,  0.6932],
        [-1.7663,  0.6918],
        ...,
        [-1.3111,  0.1877],
        [-1.3111,  0.1876],
        [-1.2482,  0.0781]], grad_fn=<AddmmBackward0>)
torch.Size([138266, 64])
tensor([[-2.0506,  1.3177],
        [-1.5204,  0.4869],
        [-0.7324, -0.0178],
        ...,
        [-1.8386,  0.5451],
        [-1.4483,  0.2214],
        [-1.4483,  0.2214]], grad_fn=<AddmmBackward0>)
torch.Size([117178, 64])
tensor([[-2.2505,  1.1702],
        [-2.250

torch.Size([118802, 64])
tensor([[-2.5896,  1.2792],
        [-2.5893,  1.2790],
        [-2.2018,  0.7052],
        ...,
        [-1.3753,  0.1042],
        [-1.7438,  0.2051],
        [-1.7437,  0.2052]], grad_fn=<AddmmBackward0>)
torch.Size([130860, 64])
tensor([[-0.4206, -0.5794],
        [-0.4194, -0.5806],
        [-0.9031,  0.0274],
        ...,
        [-1.8986,  0.7870],
        [-1.8985,  0.7872],
        [-1.4832,  0.4104]], grad_fn=<AddmmBackward0>)
torch.Size([125230, 64])
tensor([[-2.0766,  1.0021],
        [-2.0760,  1.0015],
        [-2.0769,  1.0028],
        ...,
        [-1.9580,  0.4501],
        [-2.0126,  0.4794],
        [-1.6333,  0.3187]], grad_fn=<AddmmBackward0>)
torch.Size([132446, 64])
tensor([[-1.5670,  0.7591],
        [-1.5664,  0.7586],
        [-1.9647,  1.0517],
        ...,
        [-1.6938,  0.2761],
        [-1.5651,  0.3178],
        [-2.0686,  0.5079]], grad_fn=<AddmmBackward0>)
torch.Size([122010, 64])
tensor([[-1.6606,  0.5136],
        [-1.660

torch.Size([131250, 64])
tensor([[-3.2098,  1.7333],
        [-1.6740,  0.1103],
        [-2.8434,  1.4332],
        ...,
        [-2.0423,  0.6212],
        [-1.5377,  0.2225],
        [-1.5377,  0.2224]], grad_fn=<AddmmBackward0>)
torch.Size([124906, 64])
tensor([[-2.1859,  0.8875],
        [-2.1859,  0.8874],
        [-2.1858,  0.8873],
        ...,
        [-1.8509,  0.5046],
        [-1.6405,  0.2540],
        [-1.6405,  0.2541]], grad_fn=<AddmmBackward0>)
torch.Size([124908, 64])
tensor([[-1.6925,  0.7321],
        [-1.6920,  0.7316],
        [-1.7067,  0.6240],
        ...,
        [-1.7651,  0.5241],
        [-1.5045,  0.3376],
        [-1.9994,  0.5967]], grad_fn=<AddmmBackward0>)
torch.Size([125872, 64])
tensor([[-2.7268,  1.5847],
        [-1.5294,  0.3781],
        [-0.7918, -0.3670],
        ...,
        [-1.7825,  0.5629],
        [-1.7461,  0.5633],
        [-1.7460,  0.5635]], grad_fn=<AddmmBackward0>)
torch.Size([145102, 64])
tensor([[-1.7727,  0.6708],
        [-1.772

torch.Size([113694, 64])
tensor([[-3.0124,  1.9425],
        [-2.5447,  1.2162],
        [-2.8615,  1.6666],
        ...,
        [-2.5538,  0.9107],
        [-2.5543,  0.9116],
        [-2.5541,  0.9110]], grad_fn=<AddmmBackward0>)
torch.Size([126216, 64])
tensor([[-1.0416, -0.0551],
        [-1.8136,  0.6111],
        [-1.8130,  0.6106],
        ...,
        [-1.5682,  0.3209],
        [-1.5682,  0.3208],
        [-1.5681,  0.3209]], grad_fn=<AddmmBackward0>)
torch.Size([127974, 64])
tensor([[-1.0076,  0.1296],
        [-1.0081,  0.1301],
        [-1.0072,  0.1290],
        ...,
        [-1.5572,  0.3376],
        [-1.3960,  0.2422],
        [-1.5572,  0.3376]], grad_fn=<AddmmBackward0>)
torch.Size([126634, 64])
tensor([[-1.3624,  0.2041],
        [-1.3622,  0.2039],
        [-0.0302, -0.9336],
        ...,
        [-1.3767,  0.1382],
        [-1.3767,  0.1382],
        [-1.3767,  0.1381]], grad_fn=<AddmmBackward0>)
torch.Size([126566, 64])
tensor([[-0.8929, -0.0291],
        [-0.893

torch.Size([117078, 64])
tensor([[-1.4542,  0.4740],
        [-1.4536,  0.4734],
        [-1.2600,  0.4649],
        ...,
        [-2.1943,  0.8734],
        [-2.0719,  0.8045],
        [-1.5698,  0.5177]], grad_fn=<AddmmBackward0>)
torch.Size([137238, 64])
tensor([[-2.2303,  1.2511],
        [-2.2308,  1.2516],
        [-2.7380,  1.5764],
        ...,
        [-0.9984,  0.2038],
        [-1.1652,  0.2838],
        [-1.1652,  0.2839]], grad_fn=<AddmmBackward0>)
torch.Size([119980, 64])
tensor([[-1.1034,  0.2466],
        [-1.1038,  0.2469],
        [-1.1032,  0.2461],
        ...,
        [-1.8027,  0.7175],
        [-1.3907,  0.3943],
        [-1.3745,  0.2800]], grad_fn=<AddmmBackward0>)
torch.Size([135932, 64])
tensor([[-1.6922,  0.6082],
        [-1.2816, -0.0229],
        [-1.2171,  0.0971],
        ...,
        [-1.2659,  0.4248],
        [-1.0260, -0.1035],
        [-1.0261, -0.1030]], grad_fn=<AddmmBackward0>)
torch.Size([123270, 64])
tensor([[-0.8038, -0.0621],
        [-0.803

tensor([[-2.3761,  1.0200],
        [-2.3931,  1.0857],
        [-2.3927,  1.0852],
        ...,
        [-1.3637,  0.3565],
        [-2.1353,  0.6603],
        [-2.1353,  0.6604]], grad_fn=<AddmmBackward0>)
torch.Size([128906, 64])
tensor([[-2.7538,  1.4431],
        [-2.7538,  1.4431],
        [-2.3056,  0.9098],
        ...,
        [-2.1653,  0.7675],
        [-2.1434,  0.7459],
        [-2.1654,  0.7674]], grad_fn=<AddmmBackward0>)
torch.Size([144960, 64])
tensor([[-0.4431, -0.9074],
        [-0.4440, -0.9065],
        [-1.1515, -0.0732],
        ...,
        [-1.8678,  0.4912],
        [-1.4758,  0.4037],
        [-1.4205,  0.3618]], grad_fn=<AddmmBackward0>)
torch.Size([120786, 64])
tensor([[-0.9229, -0.2718],
        [-0.9232, -0.2714],
        [ 0.6012, -1.9845],
        ...,
        [-1.6430,  0.3954],
        [-1.6430,  0.3955],
        [-1.6429,  0.3954]], grad_fn=<AddmmBackward0>)
torch.Size([148246, 64])
tensor([[-1.5006,  0.0747],
        [-1.5005,  0.0746],
        [-1.

torch.Size([135848, 64])
tensor([[-2.2766,  0.9521],
        [-2.2766,  0.9521],
        [-1.8060, -0.0174],
        ...,
        [-2.1907,  0.7453],
        [-1.8563,  0.4221],
        [-1.8564,  0.4220]], grad_fn=<AddmmBackward0>)
torch.Size([108688, 64])
tensor([[-2.4252,  1.0924],
        [-2.4258,  1.0929],
        [-2.7456,  1.4377],
        ...,
        [-2.0365,  0.5925],
        [-1.6575,  0.4359],
        [-1.6576,  0.4359]], grad_fn=<AddmmBackward0>)
torch.Size([134728, 64])
tensor([[-2.6898,  1.4314],
        [-1.7359,  0.7153],
        [-1.7365,  0.7159],
        ...,
        [-2.4375,  0.9308],
        [-2.4132,  0.8482],
        [-2.4130,  0.8484]], grad_fn=<AddmmBackward0>)
torch.Size([113464, 64])
tensor([[-1.9320,  0.5028],
        [-1.9314,  0.5022],
        [-1.9325,  0.5040],
        ...,
        [-1.8880,  0.6087],
        [-1.8880,  0.6088],
        [-1.6037,  0.3891]], grad_fn=<AddmmBackward0>)
torch.Size([136756, 64])
tensor([[-1.9844,  0.6820],
        [-1.984

torch.Size([120524, 64])
tensor([[-2.0810,  0.8842],
        [-2.0804,  0.8837],
        [-1.7679,  0.3576],
        ...,
        [-1.6016,  0.4140],
        [-1.6187,  0.4966],
        [-1.6188,  0.4962]], grad_fn=<AddmmBackward0>)
torch.Size([143658, 64])
tensor([[-0.9505, -0.0622],
        [-0.9500, -0.0627],
        [-0.9507, -0.0617],
        ...,
        [-1.3907,  0.4936],
        [-1.7607,  0.7254],
        [-1.7609,  0.7250]], grad_fn=<AddmmBackward0>)
torch.Size([143670, 64])
tensor([[ 0.0206, -1.3163],
        [ 0.0187, -1.3145],
        [-1.3245,  0.3016],
        ...,
        [-1.6478,  0.3540],
        [-1.8377,  0.4480],
        [-1.6757,  0.5286]], grad_fn=<AddmmBackward0>)
torch.Size([136702, 64])
tensor([[-2.8020,  1.3960],
        [-2.8020,  1.3961],
        [-2.5427,  1.1300],
        ...,
        [-2.0894,  0.6323],
        [-2.1331,  0.8105],
        [-1.8605,  0.5304]], grad_fn=<AddmmBackward0>)
torch.Size([120154, 64])
tensor([[-2.6924,  1.0534],
        [-2.691

torch.Size([137624, 64])
tensor([[-2.3145,  0.7464],
        [-2.3151,  0.7471],
        [-2.6420,  1.7825],
        ...,
        [-2.7619,  1.2855],
        [-2.7618,  1.2855],
        [-2.7620,  1.2855]], grad_fn=<AddmmBackward0>)
torch.Size([144160, 64])
tensor([[-2.2305,  0.4553],
        [-2.2301,  0.4550],
        [-1.4607,  0.5289],
        ...,
        [-2.4432,  0.9085],
        [-2.4432,  0.9088],
        [-2.6819,  1.1911]], grad_fn=<AddmmBackward0>)
torch.Size([128544, 64])
tensor([[-2.4579,  0.6424],
        [-1.1980, -0.6072],
        [-1.1980, -0.6072],
        ...,
        [-2.2003,  0.8047],
        [-2.4377,  1.0702],
        [-2.4376,  1.0697]], grad_fn=<AddmmBackward0>)
torch.Size([123688, 64])
tensor([[-1.1314, -0.0927],
        [-1.3709,  0.0422],
        [-1.3705,  0.0419],
        ...,
        [-2.2044,  0.8242],
        [-1.5548,  0.5524],
        [-2.2044,  0.8242]], grad_fn=<AddmmBackward0>)
torch.Size([119022, 64])
tensor([[-0.1999, -1.7731],
        [-0.239

torch.Size([107886, 64])
tensor([[-2.0539,  0.8122],
        [-2.0546,  0.8129],
        [-2.0537,  0.8117],
        ...,
        [-1.4194,  0.6443],
        [-1.5621,  0.6985],
        [-1.7079,  0.7597]], grad_fn=<AddmmBackward0>)
torch.Size([123250, 64])
tensor([[-1.9046,  0.5632],
        [-1.9053,  0.5638],
        [-2.2907,  0.6644],
        ...,
        [-1.4062,  0.5793],
        [-1.5917,  0.6825],
        [-1.5917,  0.6825]], grad_fn=<AddmmBackward0>)
torch.Size([133478, 64])
tensor([[-2.3806,  0.5817],
        [-2.3805,  0.5816],
        [-2.0773,  0.4560],
        ...,
        [-1.6450,  0.8726],
        [-1.6450,  0.8726],
        [-1.1101,  0.4754]], grad_fn=<AddmmBackward0>)
torch.Size([109172, 64])
tensor([[-2.0764,  0.1445],
        [-2.0756,  0.1438],
        [-2.9149,  1.4064],
        ...,
        [-1.1278,  0.6838],
        [-0.8094,  0.4127],
        [-1.1081,  0.5960]], grad_fn=<AddmmBackward0>)
torch.Size([119150, 64])
tensor([[-2.2363,  0.6193],
        [-2.607

torch.Size([127024, 64])
tensor([[-1.8342,  0.4827],
        [-1.8341,  0.4826],
        [-1.7815,  0.6264],
        ...,
        [-1.7973,  1.2988],
        [-1.1783,  0.7349],
        [-1.2110,  0.7506]], grad_fn=<AddmmBackward0>)
torch.Size([131610, 64])
tensor([[-1.1806,  0.1606],
        [-1.1799,  0.1599],
        [-2.2410,  0.9174],
        ...,
        [-1.4752,  0.8733],
        [-1.2845,  0.7964],
        [-1.4596,  0.8604]], grad_fn=<AddmmBackward0>)
torch.Size([116116, 64])
tensor([[-1.8054,  0.3403],
        [-1.8057,  0.3407],
        [-1.8920,  0.7439],
        ...,
        [-1.3860,  0.8283],
        [-1.3860,  0.8283],
        [-1.4830,  0.8766]], grad_fn=<AddmmBackward0>)
torch.Size([132840, 64])
tensor([[-1.5161,  0.3215],
        [-2.1158,  0.6425],
        [-2.1163,  0.6442],
        ...,
        [-1.7362,  1.3089],
        [-1.5710,  0.9746],
        [-1.6133,  0.9490]], grad_fn=<AddmmBackward0>)
torch.Size([140970, 64])
tensor([[-2.8939,  1.4747],
        [-2.894

torch.Size([121746, 64])
tensor([[-2.1471,  0.9175],
        [-2.1478,  0.9182],
        [-2.1471,  0.9173],
        ...,
        [-1.4019,  0.5824],
        [-1.4513,  0.6160],
        [-1.4513,  0.6160]], grad_fn=<AddmmBackward0>)
torch.Size([111834, 64])
tensor([[-1.1417, -0.2228],
        [-1.1411, -0.2234],
        [-0.9618, -0.2695],
        ...,
        [-1.3832,  0.6061],
        [-1.7417,  0.8549],
        [-1.7416,  0.8549]], grad_fn=<AddmmBackward0>)
torch.Size([126410, 64])
tensor([[-1.4492,  0.1984],
        [-1.4490,  0.1982],
        [-1.4491,  0.1983],
        ...,
        [-1.3678,  0.5624],
        [-1.3678,  0.5623],
        [-1.3677,  0.5624]], grad_fn=<AddmmBackward0>)
torch.Size([119742, 64])
tensor([[-2.2043,  1.0129],
        [-1.7711,  0.7512],
        [-1.7708,  0.7508],
        ...,
        [-1.3596,  0.5009],
        [-1.5694,  0.6622],
        [-1.5694,  0.6621]], grad_fn=<AddmmBackward0>)
torch.Size([127852, 64])
tensor([[-1.9124,  0.7716],
        [-1.156

torch.Size([127898, 64])
tensor([[-1.9339,  0.1901],
        [-1.9340,  0.1901],
        [-2.8537,  1.2454],
        ...,
        [-2.0084,  0.9847],
        [-2.0258,  1.2558],
        [-1.8875,  0.9443]], grad_fn=<AddmmBackward0>)
torch.Size([125154, 64])
tensor([[-1.7299,  0.4006],
        [-1.7304,  0.4012],
        [-1.6338,  0.1441],
        ...,
        [-1.5520,  0.6387],
        [-2.3062,  1.0289],
        [-2.3060,  1.0289]], grad_fn=<AddmmBackward0>)
torch.Size([136290, 64])
tensor([[-1.3845,  0.3136],
        [-1.3839,  0.3129],
        [-1.3865,  0.3160],
        ...,
        [-1.7931,  0.9144],
        [-1.7931,  0.9144],
        [-1.7931,  0.9144]], grad_fn=<AddmmBackward0>)
torch.Size([145042, 64])
tensor([[-2.4792,  0.7911],
        [-2.3970,  0.6309],
        [-2.3972,  0.6310],
        ...,
        [-2.3049,  1.2852],
        [-2.0781,  1.2315],
        [-1.2576,  0.6215]], grad_fn=<AddmmBackward0>)
torch.Size([128736, 64])
tensor([[-1.6696,  0.6831],
        [-1.670

torch.Size([135968, 64])
tensor([[-2.5713,  0.8675],
        [-2.8217,  1.6560],
        [-2.7448,  1.4057],
        ...,
        [-1.2437,  0.7209],
        [-1.7263,  1.2292],
        [-1.7262,  1.2292]], grad_fn=<AddmmBackward0>)
torch.Size([120716, 64])
tensor([[-2.9015,  1.4621],
        [-2.8452,  0.9468],
        [-2.8455,  0.9470],
        ...,
        [-1.1451,  0.5930],
        [-1.0832,  0.5654],
        [-1.0831,  0.5654]], grad_fn=<AddmmBackward0>)
torch.Size([133548, 64])
tensor([[-1.4760,  0.2581],
        [-1.4752,  0.2574],
        [-1.4760,  0.2587],
        ...,
        [-0.9590,  0.4420],
        [-1.1052,  0.5243],
        [-1.1850,  0.6951]], grad_fn=<AddmmBackward0>)
torch.Size([140166, 64])
tensor([[-1.7086,  0.1237],
        [-1.4115, -0.1213],
        [-1.9022,  0.9885],
        ...,
        [-1.3556,  0.8487],
        [-0.9569,  0.4911],
        [-0.9568,  0.4910]], grad_fn=<AddmmBackward0>)
torch.Size([109998, 64])
tensor([[-1.5772,  0.0696],
        [-1.577

torch.Size([133534, 64])
tensor([[-2.0010,  0.7995],
        [-2.0019,  0.8004],
        [-2.3086,  0.9571],
        ...,
        [-1.1918,  0.5450],
        [-1.1917,  0.5448],
        [-1.4394,  0.8558]], grad_fn=<AddmmBackward0>)
torch.Size([115584, 64])
tensor([[-2.0137,  0.9511],
        [-1.5761,  0.0608],
        [-1.7499,  0.2317],
        ...,
        [-1.2463,  0.6279],
        [-0.9854,  0.4980],
        [-0.9855,  0.4982]], grad_fn=<AddmmBackward0>)
torch.Size([134534, 64])
tensor([[-0.9140, -0.7285],
        [-0.9148, -0.7279],
        [-2.3298,  0.8829],
        ...,
        [-0.9661,  0.4944],
        [-1.0331,  0.5110],
        [-1.4128,  0.8471]], grad_fn=<AddmmBackward0>)
torch.Size([128578, 64])
tensor([[-2.9033,  1.4608],
        [-2.9036,  1.4609],
        [-2.3716,  0.9682],
        ...,
        [-1.1243,  0.6394],
        [-1.1244,  0.6394],
        [-1.4468,  1.0020]], grad_fn=<AddmmBackward0>)
torch.Size([104652, 64])
tensor([[-1.9344,  0.7811],
        [-1.935

In [52]:
# Test the model
model.eval()
with torch.no_grad():
    for graph_data in loader:
        output = model(graph_data.x, graph_data.edge_index)
        pred = output.argmax(dim=1)
        correct = pred.eq(graph_data.y).sum().item()
        accuracy = correct / graph_data.y.size(0)
        print('Accuracy: {:.4f}'.format(accuracy))

torch.Size([116642, 64])
Accuracy: 0.9170
torch.Size([127298, 64])
Accuracy: 0.9153
torch.Size([121064, 64])
Accuracy: 0.9144
torch.Size([124730, 64])
Accuracy: 0.9175
torch.Size([127558, 64])
Accuracy: 0.9171
torch.Size([139878, 64])
Accuracy: 0.9222
torch.Size([118646, 64])
Accuracy: 0.9148
torch.Size([134194, 64])
Accuracy: 0.9189
torch.Size([129030, 64])
Accuracy: 0.9153
torch.Size([134446, 64])
Accuracy: 0.9189
torch.Size([130848, 64])
Accuracy: 0.9225
torch.Size([123130, 64])
Accuracy: 0.9150
torch.Size([135848, 64])
Accuracy: 0.9177
torch.Size([108688, 64])
Accuracy: 0.9151
torch.Size([134728, 64])
Accuracy: 0.9204
torch.Size([113464, 64])
Accuracy: 0.9122
torch.Size([136756, 64])
Accuracy: 0.9212
torch.Size([111750, 64])
Accuracy: 0.9145
torch.Size([125452, 64])
Accuracy: 0.9188
torch.Size([135226, 64])
Accuracy: 0.9209
torch.Size([110908, 64])
Accuracy: 0.9136
torch.Size([119316, 64])
Accuracy: 0.9170
torch.Size([126074, 64])
Accuracy: 0.9163
torch.Size([95366, 64])
Accuracy: 

torch.Size([123176, 64])
Accuracy: 0.9184
torch.Size([133562, 64])
Accuracy: 0.9188
torch.Size([125432, 64])
Accuracy: 0.9185
torch.Size([132940, 64])
Accuracy: 0.9221
torch.Size([123608, 64])
Accuracy: 0.9226
torch.Size([127958, 64])
Accuracy: 0.9177
torch.Size([132284, 64])
Accuracy: 0.9150
torch.Size([121188, 64])
Accuracy: 0.9192
torch.Size([138424, 64])
Accuracy: 0.9213
torch.Size([142176, 64])
Accuracy: 0.9186
torch.Size([118788, 64])
Accuracy: 0.9121
torch.Size([140274, 64])
Accuracy: 0.9229
torch.Size([140624, 64])
Accuracy: 0.9207
torch.Size([114720, 64])
Accuracy: 0.9147
torch.Size([125866, 64])
Accuracy: 0.9195
torch.Size([119998, 64])
Accuracy: 0.9203
torch.Size([145842, 64])
Accuracy: 0.9261
torch.Size([113694, 64])
Accuracy: 0.9133
torch.Size([126216, 64])
Accuracy: 0.9156
torch.Size([127974, 64])
Accuracy: 0.9122
torch.Size([126634, 64])
Accuracy: 0.9133
torch.Size([126566, 64])
Accuracy: 0.9174
torch.Size([120256, 64])
Accuracy: 0.9108
torch.Size([137520, 64])
Accuracy: